### ISSUE TITLE
Azure AD Graph API to Microsoft Graph API

### ISSUE THREAD

**Issue by sahilvas** [aquasecurity/cloudsploit#1354]
Hello, are there any plans to migrate Azure AD Graph API to Microsoft Graph API. Some of the Azure plugins have stopped working since Microsoft has deprecated Azure AD based graph API.

**Comment by alphadev4** [comment]
hi @sahilvas can you provide the name of the plugins which are not working for you?

**Comment by alphadev4** [comment]
Closing this issue due to no reply.
