### ISSUE TITLE
Azure plugin DB Restorable showing result 'SQL Database is not restorable'

### ISSUE THREAD

**Issue by jmherning** [aquasecurity/cloudsploit#1373]
I Think the Azure plugin DB Restorable is broken.

I noticed that it uses the servers:listSql and databases:listByServer apis

https://github.com/aquasecurity/cloudsploit/blob/d7b1e53fe59b41c4778b5f877ebedca27aec833f/plugins/azure/sqldatabases/dbRestorable.js#L12

in the azure collector you can see that databases:listByServer is using api version 2017-10-01-preview

https://github.com/aquasecurity/cloudsploit/blob/a04f21490f5ebe3bb64ad08abef7c358129094ac/collectors/azure/collector.js#L486-L491

But if you look at the azure rest api you can see that version 2017-10-01 does not yet include an option to listByServer. Not sure if updating to a newer api version would break anything here.

**Comment by alphadev4** [comment]
hi @jmherning azure provide multiple versions of their api. Currently this is the rest api call that cloudsploit is using 
https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/operations?api-version=2017-10-01-preview

you can read the more details from this -> link https://learn.microsoft.com/en-us/rest/api/sql/2017-10-01-preview/database-operations/list-by-database?tabs=HTTP

Thanks. We will consider updating the  version in future. 

please let us know if you have more questions.
