### ISSUE TITLE
Azure virtualNetworks error

### ISSUE THREAD

**Issue by jsherm-fwdsec** [aquasecurity/cloudsploit#1581]
Hi all. I'm getting an error with the `virtualNetworkRuleEnabled` rule, when trying to run an Azure scan:

![image](https://user-images.githubusercontent.com/87384545/224781416-76468a74-a574-49db-8cef-d3ec9f0751c1.png)

I've also tried suppressing that error from the plugin with `--suppress "virtualNetworkRuleEnabled:*:*"`, but that doesn't seem to help.

Any ideas?

**Comment by alphadev4** [comment]
Hi @jsherm-fwdsec , is the problem still there? or we should close this issue?

**Comment by jsherm-fwdsec** [comment]
Hi @alphadev4, the issue still appears to be present.

**Comment by alphadev4** [comment]
have you tried fetching the latest pull?

**Comment by alphadev4** [comment]
Hello @jsherm-fwdsec, hope you are doing good. Should we close this issue?

**Comment by alphadev4** [comment]
Closing this issue due to no response
