### ISSUE TITLE
Permission denied to list services for consumer container

### ISSUE THREAD

**Issue by agileknight** [aquasecurity/cloudsploit#1606]
When using the plugin `assetInventoryEnabled`, I get this error with the audit role permissions described in the documentation:

```
Permission denied to list services for consumer container [projects/###########] Help Token: ####################
```

The plugin works when I add the following permission to the organization audit role:
`serviceusage.services.list`

**Comment by alphadev4** [comment]
hi @agileknight Thanks for your contribution, we have updated the guide.

**Comment by comk88** [comment]
I add service usage viewer  role, ---> solved
