### ISSUE TITLE
Cannot get Cloudsploit to run.

### ISSUE THREAD

**Issue by ws8n** [aquasecurity/cloudsploit#1671]
I can't seem to get Cloudsploit to work. Any suggestions?

![image](https://github.com/aquasecurity/cloudsploit/assets/136807879/e61b23cf-8f91-4488-8006-0f42ffa37526)

**Comment by ws8n** [comment]
Got docker to work, although I had to make changes to Dockerfile as listed in 
https://github.com/aquasecurity/cloudsploit/issues/1118

**Comment by AkhtarAmir** [comment]
@ws8n we are looking into it

**Comment by alphadev4** [comment]
Hi @ws8n can you try now? Its been fixed now.

**Comment by alphadev4** [comment]
closing this issue
