### ISSUE TITLE
alibaba plugin error

### ISSUE THREAD

**Issue by INT2ECALL** [aquasecurity/cloudsploit#1723]
root@ubuntu-linux-22-04-desktop:/home/parallels/Desktop/cloudsploit# ./index.js --config=/home/parallels/Desktop/cloudsploit/config.js

   _____ _                 _  _____       _       _ _   
  / ____| |               | |/ ____|     | |     (_) |  
 | |    | | ___  _   _  __| | (___  _ __ | | ___  _| |_ 
 | |    | |/ _ \| | | |/ _` |\___ \| '_ \| |/ _ \| | __|
 | |____| | (_) | |_| | (_| |____) | |_) | | (_) | | |_ 
  \_____|_|\___/ \__,_|\__,_|_____/| .__/|_|\___/|_|\__|
                                   | |                  
                                   |_|                  

  CloudSploit by Aqua Security, Ltd.
  Cloud security auditing for AWS, Azure, GCP, Oracle, and GitHub

INFO: Using CloudSploit config file: /home/parallels/Desktop/cloudsploit/config.js
ERROR: Config file could not be loaded. Please ensure you have copied the config_example.js file to config.js`

**Comment by INT2ECALL** [comment]
// CloudSploit config file

module.exports = {
    credentials: {
        alibaba: {
            // OPTION 1: If using a credential JSON file, enter the path below
            // credential_file: '/path/to/file.json',
            // OPTION 2: If using hard-coded credentials, enter them below
            access_key: xxxxx,
            access_key_secret: xxxx,
        },
        aws: {
            // OPTION 1: If using a credential JSON file, enter the path below
            // credential_file: '/path/to/file.json',
            // OPTION 2: If using hard-coded credentials, enter them below
            // access_key: process.env.AWS_ACCESS_KEY_ID || '',
            // secret_access_key: process.env.AWS_SECRET_ACCESS_KEY || '',
            // session_token: process.env.AWS_SESSION_TOKEN || '',
            // plugins_remediate: ['bucketEncryptionInTransit']
        },
`

**Comment by INT2ECALL** [comment]
@drewblas help

**Comment by fatima99s** [comment]
@INT2ECALL  try  ./index.js --config=/home/parallels/Desktop/cloudsploit/config_example.js

**Comment by INT2ECALL** [comment]
@fatima99s solve it, by using credential_file and write json like blow

{
    "accessKeyId": "a",
    "accessKeySecret": "c"
}
