### ISSUE TITLE
Region and Resource field data mismatch

### ISSUE THREAD

**Issue by AbhinavCSY** [aquasecurity/cloudsploit#1733]
One of our scan results for AWS cloud account shows the resource value in the region field, Is it a known issue and already fixed? 
![image](https://github.com/aquasecurity/cloudsploit/assets/84574699/40814a7c-eadd-4517-814d-d42d4b980ca7)

**Comment by alphadev4** [comment]
hi @AbhinavCSY , It is a bug, and we are looking into it.

**Comment by alphadev4** [comment]
Closing this issue now.
