### ISSUE TITLE
Where does the list of bad ciphers come from?

### ISSUE THREAD

**Issue by nduthoit** [aquasecurity/cloudsploit#19]
Could you explain where/how the list of insecure ciphers in [insecureCiphers.js](https://github.com/cloudsploit/scans/blob/master/plugins/ec2/insecureCiphers.js) was generated?

We got a couple of hits for insecure ciphers when running cloudsploit on our AWS account. We're using the [recommended configuration from Mozilla (modern compatibility)](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) which includes some of the ciphers that cloudsploit flags as insecure.

Thanks,

**Comment by captn3m0** [comment]
Not very sure but clodsploit seems to be doing a substring match, which will give false positives.

```bash
# This is what it seems to be doing
$ grep -f bad.txt  modern.txt 
ECDHE-RSA-AES128-GCM-SHA256
ECDHE-RSA-AES128-SHA256
ECDHE-RSA-AES256-GCM-SHA384
ECDHE-RSA-AES256-SHA384

# When it should do this
$ grep -wf bad.txt  modern.txt 

$ grep -wf bad.txt  intermediate.txt 
DHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES128-SHA
DHE-RSA-AES128-SHA256
DHE-RSA-AES256-GCM-SHA384
DHE-RSA-AES256-SHA
DHE-RSA-AES256-SHA256
EDH-RSA-DES-CBC3-SHA

$ grep -wf bad.txt  old.txt 
DHE-DSS-AES128-GCM-SHA256
DHE-DSS-AES128-SHA256
DHE-DSS-AES256-SHA
DHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES128-SHA
DHE-RSA-AES128-SHA256
DHE-RSA-AES256-SHA
DHE-RSA-AES256-SHA256
```

It's still surprising that it finds 7 issues with the intermediate config though.

The old/modern/intermediate.txt files are generated from https://github.com/mozilla/server-side-tls/blob/gh-pages/ssl-config-generator/index.html

[bad.txt](https://github.com/cloudsploit/scans/files/1986866/bad.txt)
[intermediate.txt](https://github.com/cloudsploit/scans/files/1986867/intermediate.txt)
[modern.txt](https://github.com/cloudsploit/scans/files/1986868/modern.txt)
[old.txt](https://github.com/cloudsploit/scans/files/1986869/old.txt)
