### ISSUE TITLE
Unable to query storage buckets with default privileges

### ISSUE THREAD

**Issue by Yashvendra** [aquasecurity/cloudsploit#243]
The service account we create for CloudSploit on GCP with the default permission shows this error when trying to showcase information regarding buckets.
```
StorageBucket All Users Policy -> UNKNOWN Unable to query storage buckets does not have storage.buckets.getIamPolicy access to the Google Cloud Storage bucket.
```
But when we give _storage admin permission_ to the CloudSploit service account, it is able to query the buckets. 

Is there any way we can get the results for buckets with the read-only permissions?

**Comment by matthewdfuller** [comment]
Hi @Yashvendra - please try adding the `Storage Account Key Operator Service Role` role to the application? You can read more about this requirement [here](https://cloudsploit.freshdesk.com/support/solutions/articles/17000104617-azure-storage-account-file-service-queue-service-table-service-unknown-results).
