### ISSUE TITLE
Support for private clouds like OpenStack

### ISSUE THREAD

**Issue by SyCode7** [aquasecurity/cloudsploit#30]
Hi,  this is not an issue but a feature request. Do you plan to extend CloudSploit capacities to open source clouds like OpenStack ? This could be a very interesting feature...

**Comment by matthewdfuller** [comment]
Hi @SyCode7 thanks for the request - we do not have plans to support OpenStack at the moment, but do welcome others to +1 this post as a means of voting it up.

**Comment by SyCode7** [comment]
@matthewdfuller , thanks for responding. What are the options for extending CloudSpoit if someone is interested in doing this ? Are there APIs e.t.c for other cloud providers or licensing issues ?
