### ISSUE TITLE
How to write a plugin that depends on post-postcalls? (calls 3+ levels deep)

### ISSUE THREAD

**Issue by stevekrouse** [aquasecurity/cloudsploit#335]
How would one write a plugin that requires calling apis in a sequence of 3+? It seems that the postcalls array handles calling services in a sequence of 2 only. It doesn't seem to do anything smart (such as waiting for reliesOnCalls to return), but simply returns if the data isn't there when it looks:

https://github.com/aquasecurity/cloudsploit/blob/4b21ff31e23142ec5f4958132cb550ea369818e2/collectors/aws/collector.js#L1124-L1129

To be more concrete, here's my desired additions to `postcalls`:

```js
ECR: {
    listImages: {
        reliesOnService: 'ecr',
        reliesOnCall: 'describeRepositories',
        filterKey: 'repositoryName',
        filterValue: 'repositoryName',
        paginate: 'nextToken',
        params: {
            maxResults: 1000,
            Filters: [
                {
                    Name: 'tagStatus',
                    Values: [
                        'TAGGED'
                    ]
                }
            ]
        },
    }
    describeImageScanFindings: {
        reliesOnService: 'ecr',
        reliesOnCall: 'listImages', # this is the troublesome line
         override: true
    }
}
```

The `reliesOnCall: 'listImages'` is the troublesome line because it requires `listImages` to finish before it can run, leading to a sequence three levels deeps: `describeRepositories` -> `listImages` -> `describeImageScanFindings`. 

What's the most Cloudsploit-idiomatic way to write this? Thanks!

-----------------------

Side question: is it possible to write `describeImageScanFindings` without `override: true`? The reason I currently have it that way is because it requires two filterKeys: `repositoryName` and `imageId`. Does cloudsploit support two filter keys?

Thanks!

**Comment by giorod3** [comment]
@stevekrouse In the AWS collector you will notice that postcalls is an array that contains two objects. If you put describeImageScanFindings in the second array with the reliesOnCall being 'describeRepositories' and listImages in the first array you will get the desired outcome. Here is where the second object begins: https://github.com/aquasecurity/cloudsploit/blob/master/collectors/aws/collector.js#L984.

We also do not support two filter keys. using the override flag and a custom collector file are necessary.

**Comment by stevekrouse** [comment]
Very helpful, thank you!
