### ISSUE TITLE
Node exception: syntax error in argparse.js: "syntax error: unexpected token {"

### ISSUE THREAD

**Issue by theotherothermatt** [aquasecurity/cloudsploit#370]
While trying to set up Cloudsploit scanner in Azure VM, am presented with this error on run:
```
azureuser@cloudsploit-master:~/scans$ ./index.js -h
/home/azureuser/scans/node_modules/argparse/argparse.js:222
    } catch {}
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/azureuser/scans/index.js:3:28)

```
The block of code in question:
```
function _alias(object, from, to) {
    try {
        let name = object.constructor.name
        Object.defineProperty(object, from, {
            value: util.deprecate(object[to], sub('%s.%s() is renamed to %s.%s()',
                name, from, name, to)),
            enumerable: false
        })
    } catch {}
}
```
I am not a developer, but it seems to me that the "catch" is missing the variable to catch. On this assumption, I changed the catch to
```
...
   } catch (e) {}
}
```
And was then able to view the usage information as expected.

OS: Ubuntu 18.04
Node version: v8.10.0
NPM version: 3.5.2

Steps to reproduce:

1. Create new Ubuntu instance
2. Install NPM (apt-get install npm)
3. Follow instructions for quick start from Readme.md

**Comment by saifuddin123** [comment]
I updated the ../node_modules/argparse/argparse.js:222 with  } catch (exp) {} and it fixed it

**Comment by theotherothermatt** [comment]
This is an issue with Node's argparse, not Cloudsploit. Closing.
