### ISSUE TITLE
Error with monitoringMetrics plugin (AWS)

### ISSUE THREAD

**Issue by abernalneo** [aquasecurity/cloudsploit#509]
Hello everyone.
I found the following issue: when I executed specific plugin monitoringMetrics there is an error. This is what it happens:

./index.js --config ./config.js --plugin=monitoringMetrics

   _____ _                 _  _____       _       _ _
  / ____| |               | |/ ____|     | |     (_) |
 | |    | | ___  _   _  __| | (___  _ __ | | ___  _| |_
 | |    | |/ _ \| | | |/ _` |\___ \| '_ \| |/ _ \| | __|
 | |____| | (_) | |_| | (_| |____) | |_) | | (_) | | |_
  \_____|_|\___/ \__,_|\__,_|_____/| .__/|_|\___/|_|\__|
                                   | |
                                   |_|

  CloudSploit by Aqua Security, Ltd.
  Cloud security auditing for AWS, Azure, GCP, Oracle, and GitHub

INFO: Using CloudSploit config file: ./config.js
INFO: Skipping AWS pagination mode
INFO: Testing plugin: CloudWatch Monitoring Metrics
INFO: Determining API calls to make...
INFO: Found 2 API calls to make for aws plugins
INFO: Collecting metadata. This may take several minutes...
INFO: Metadata collection complete. Analyzing...
INFO: Analysis complete. Scan report to follow...
Plugin CloudWatch Monitoring Metrics returned no results. There may be a problem with this plugin.
/home/neosecure/cloudsploit/node_modules/tty-table/src/format.js:172
            + Array(padBoth + 1 + padRemainder).join(" ")
              ^

RangeError: Invalid array length
    at /home/neosecure/cloudsploit/node_modules/tty-table/src/format.js:172:15
    at Array.map (<anonymous>)
    at Object.module.exports.wrapCellText (/home/neosecure/cloudsploit/node_modules/tty-table/src/format.js:156:35)
    at Object.module.exports.buildCell (/home/neosecure/cloudsploit/node_modules/tty-table/src/render.js:287:39)
    at /home/neosecure/cloudsploit/node_modules/tty-table/src/render.js:171:26
    at Array.map (<anonymous>)
    at Object.module.exports.buildRow (/home/neosecure/cloudsploit/node_modules/tty-table/src/render.js:170:13)
    at /home/neosecure/cloudsploit/node_modules/tty-table/src/render.js:47:24
    at Array.map (<anonymous>)
    at Object.module.exports.stringifyData (/home/neosecure/cloudsploit/node_modules/tty-table/src/render.js:46:45)

A few days ago I was working with this plugin and it was working just fine.

**Comment by giorod3** [comment]
We have just implemented a fix for this. Please pull from master and try again.

**Comment by abernalneo** [comment]
I tried again. Same error

**Comment by abernalneo** [comment]
Just to confirm that this failed behaviour only happens in this scenario: there is no trail configured on AWS and Cloudsploit runs for that specific plugin i.e --plugin=monitoringMetrics. If I run a --compliance=cis it works perfectly.
