### ISSUE TITLE
Error when running on Docker

### ISSUE THREAD

**Issue by matiassequeira** [aquasecurity/cloudsploit#946]
Hello, I'm getting an error when trying to run cloudsploit on Docker by following your instructions:

```
❯ cd cloudsploit
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
❯ docker build . -t cloudsploit:0.0.1
[+] Building 1.8s (8/8) FINISHED                                                                                          
❯ docker run cloudsploit:0.0.1 -h
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "cloudsploit-scan": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled
```

Let me know any other information you might need. Also, I'd be happy to send you a PR to fix it

**Comment by benjaminwestern** [comment]
I have had the same issue.  Inside the container /var/scan/node_modules/.bin/ contains a file called cloudsploitscan however the endpoint in the docker file references the file as cloudsploit-scan. Updating the entrypoint to cloudsploitscan the issue is resolved.

**Comment by RickBankers** [comment]
Can someone tell me how to run a scan against azure via docker? I fixed the entrypoint issue but when I run the following I get error messages

`docker run -e AZURE_APPLICATION_ID=12345 -e AZURE_KEY_VALUE=12345 -e AZURE_DIRECTORY_ID=12345 -e AZURE_SUBSCIPTION_ID=12345 cloudsploit:0.0.1`

NFO: Collecting metadata. This may take several minutes...
/var/scan/node_modules/azure-arm-compute/lib/computeManagementClient.js:46
      throw new Error('\'subscriptionId\' cannot be null.');
      ^

Error: 'subscriptionId' cannot be null.
    at new ComputeManagementClient (/var/scan/node_modules/azure-arm-compute/lib/computeManagementClient.js:46:13)

**Comment by seanramos** [comment]
@RickBankers How did you go about fixing the entrypoint issue?

**Comment by tharinduscybers** [comment]
Why the PR https://github.com/aquasecurity/cloudsploit/pull/969/files is still not merged? After adding this fix, the issue gets resolved.

**Comment by evaldasou** [comment]
anyone works on this project? 
I check 9 months later and seems only issue why cloudsploit is not working is this PR : 
https://github.com/aquasecurity/cloudsploit/pull/969/files Can You finally merge it please? :)
